from Graphics import *

def create_map(world):
	n1= world.add_node(Point(100,50), "1")
	n2 = world.add_node(Point(200,25), "2")
	n3 = world.add_node(Point(200,115), "3")
	n4 = world.add_node(Point(300,50), "4")
	n5 = world.add_node(Point(400,50), "5")
	n6 = world.add_node(Point(400,115), "6")
	n7 = world.add_node(Point(450,400), "7")
	n8 = world.add_node(Point(375,385), "8")
	n9 = world.add_node(Point(375,450), "9")
	n10 = world.add_node(Point(300,350), "10")
	n11 = world.add_node(Point(275,450), "11")
	n12 = world.add_node(Point(175,385), "12")
	n13 = world.add_node(Point(100,315), "13")
	n14 = world.add_node(Point(50,450), "14")
	n15 = world.add_node(Point(50,150), "15")

	world.link(n1, n2)
	world.link(n1, n3)
	world.link(n1, n4)
	world.link(n1, n13)
	world.link(n1, n15)
	world.link(n2, n4)
	world.link(n3, n6)
	world.link(n4, n5)
	world.link(n5, n6)
	world.link(n6, n7)
	world.link(n6, n8)
	world.link(n7, n9)
	world.link(n7, n8)
	world.link(n8, n9)
	world.link(n8, n10)
	world.link(n9, n10)
	world.link(n9, n11)
	world.link(n10, n11)
	world.link(n10, n12)
	world.link(n11, n12)
	world.link(n11, n14)
	world.link(n12, n13)
	world.link(n13, n14)
	world.link(n14, n15)

	park = Rectangle(Point(150, 150), Point(350, 300))
	park.setFill("green")
	park.draw_once(world.get_world())
	park_text = Text(Point(170, 290), "park")
	park_text.draw_once(world.get_world())
	lake = Oval(Point(160, 160), Point(285, 260))
	lake.setFill("blue")
	lake.draw_once(world.get_world())
	lake_text = Text(Point(222, 210), "Pond")
	lake_text.setSize(15)
	lake_text.draw_once(world.get_world())
	dogeness(world)
	world.draw_nodes()

def dogeness(world):
	cow = Oval(Point(300, 250), Point(330, 270))
	cow.setFill("white")
	cow.draw_once(world.get_world())
	cow_head = Circle(Point(330, 250), 5)
	cow_head.setFill("white")
	cow_head.draw_once(world.get_world())
	cow_spot1 = Oval(Point(307, 255), Point(313, 260))
	cow_spot1.setFill("black")
	cow_spot1.draw_once(world.get_world())
	cow_spot2 = Oval(Point(317, 259), Point(324, 265))
	cow_spot2.setFill("black")
	cow_spot2.draw_once(world.get_world())
	cow_text = Text(Point(315, 280), "COW")
	cow_text.setSize(8)
	cow_text.draw_once(world.get_world())
	moo = Text(Point(340, 240), "Moo")
	moo.setSize(7)
	moo.draw_once(world.get_world())
	such = Text(Point(450, 75), "Such")
	artistic = Text(Point(450, 95), "Artistic")
	such.setTextColor("Magenta")
	artistic.setTextColor("Magenta")
	such.setStyle("bold")
	artistic.setStyle("bold")
	such.setSize(14)
	artistic.setSize(14)
	such.draw_once(world.get_world())
	artistic.draw_once(world.get_world())
	very = Text(Point(30, 225), "Very")
	vcow = Text(Point(30, 250), "Cow")
	very.setStyle("bold italic")
	vcow.setStyle("bold italic")
	very.setTextColor("purple")
	vcow.setTextColor("purple")
	very.setSize(18)
	vcow.setSize(18)
	very.draw_once(world.get_world())
	vcow.draw_once(world.get_world())
	much = Text(Point(450, 450), "MUCH")
	wow = Text(Point(450, 475), "WOW")
	much.setSize(20)
	wow.setSize(24)
	much.setStyle("bold")
	wow.setStyle("bold")
	much.setTextColor("salmon")
	wow.setTextColor("salmon")
	much.draw_once(world.get_world())
	wow.draw_once(world.get_world())
	mooo = Text(Point(200, 480), "MOOOOOOO")
	mooo.setSize(30)
	mooo.setTextColor("red")
	mooo.setStyle("bold")
	mooo.draw_once(world.get_world())

def option_1(world, robot_radius):
	create_map(world)
	robot = world.add_robot(world.get_nodes()[0].get_point(), world, robot_radius)
	world.draw_objects()

	while True:
		while True:
			usrinput = raw_input("Enter a node to navigate to: ")
			found, node = world.find_node_from_string(usrinput)
			if found:
				goal = node
				break
			print "Invalid Node!"
		world.nav(robot, goal)